# ==========================================================
# CONFIGURAÇÕES GERAIS DA APLICAÇÃO
# ==========================================================
spring.application.name=api
server.port=8080

# Gerenciamento de JSON: Converte camelCase (Java) para snake_case (JSON/API)
# Resolve o problema de padronização estética nas respostas da API para o Angular.
spring.jackson.property-naming-strategy=SNAKE_CASE

# ==========================================================
# PERSISTÊNCIA RELACIONAL (POSTGRESQL)
# ==========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/idealcomputer_db
spring.datasource.username=postgres
spring.datasource.password=post

# Dialeto e Comportamento do Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================================
# PERSISTÊNCIA NOSQL (ELASTICSEARCH)
# ==========================================================
# Define o endpoint para o motor de busca e recomendações.
spring.elasticsearch.uris=http://localhost:9200

# ==========================================================
# SEGURANÇA E AUTENTICAÇÃO (JWT)
# ==========================================================
# Chave de assinatura para os Tokens JWT e tempo de expiração (10 horas)
jwt.secret=idealcomputer_esta_e_uma_chave_secreta_muito_maior_e_mais_segura_para_usar_em_producao_2025
jwt.expiration=36000000